name: .NET Framework Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: Namalyzer.sln
      Project_Directory: Namalyzer
      Project_Path: Namalyzer.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.2.0

    - name: Restore nuget packages
      run: nuget restore $env:Solution_Name

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=Release /p:DefineConstants=CI_BUILD -p:OutDir="out/"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Result
        path: ${{ env.Project_Directory }}\out
